lookup_spv_frd <- function(){
  lookuptable <- data.table(SP_VEGI = c("A", "AC", "ACB", "ACT", "AD", "AH", "AT",
                                        "AX", "B", "BA", "BB", "BC", "BG", "BL", "BM", 
                                        "BP", "C", "CI", "CP", "CW", "CY", "D", "DG",
                                        "DM", "DR", "DS", "E", "EA", "EB", "EE", "EP",
                                        "ES", "EW", "EXP", "EY", "F", "FD", 
                                        "FDC", "FDI", "G", "GP", "H", "HM", "HW",
                                        "HXM", "IG", "IS", "J", "JR", "K", "KC", "L", 
                                        "LA", "LD", "LE", "LT", "LW", "M", 
                                        "MB", "ME", "MN", "MR", "MS", "MV", "OA", "OB",
                                        "OC", "OD", "OE", "OF", "OG", "OH", "OI", "P", 
                                        "PA", "PF", "PJ", "PL", "PLC", "PLI", 
                                        "PM", "PR", "PS", "PW", "PXJ", "PY", "Q",
                                        "QE", "QG", "QW", "R", "RA", "S", "SA", "SB", 
                                        "SE", "SN", "SS", "SW", "SX", "SXB", "SXE", 
                                        "SXL", "SXS", "SXW", "SXX", "T", "TW", "U", 
                                        "UA", "UP", "V", "VB", "VP", "VS", "VV", "W", 
                                        "WA", "WB", "WD", "WP", "WS", "WT", 
                                        "X", "XC", "XH", "Y", "YC", "YP", "Z",
                                        "ZC", "ZH"),
                            SP_FRED = c("AT", "ACB", "ACB", "ACT", "ACT", "ACT", 
                                        "AT", "ACB", "BA", "BA", "BL", "BA", "BA", "BL", "BA", "BP", 
                                        "CW", "CW", "CW", "CW", "CW", "DR", "DR", "DR", "DR", "DR", 
                                        "AT", "AT", "AT", "AT", "AT", "AT", "AT", "AT", "AT", "FD", 
                                        "FD", "FDC", "FDI", "DR", "DR", "HW", "HWC", "HW", "HWC", 
                                        "CW", "CW", "CW", "CW", "AT", "AT", "LW", "LW", "LW", "LW", 
                                        "LW", "LW", "DR", "DR", "DR", "DR", "DR", "DR", "DR", "CW", 
                                        "CW", "CW", "AT", "AT", "AT", "AT", "AT", "AT", "PL", "PL", 
                                        "PL", "PL", "PL", "PL", "PL", "PL", "PL", "PL", "PW", "PL", 
                                        "PY", "AT", "AT", "AT", "AT", "DR", "DR", "S", "SW", "SB", 
                                        "SW", "SW", "SS", "SW", "SW", "SW", "SS", "SS", "SS", "SW", 
                                        "SW", "HWC", "HWC", "AT", "AT", "AT", "AT", "AT", "AT", "AT", 
                                        "AT", "AT", "AT", "AT", "AT", "AT", "AT", "AT", "FD", "FD", 
                                        "AT", "CW", "CW", "CW", "FD", "FD", "AT"))
  return(lookuptable)
}